server :
  port : 9090
  tomcat :
    uriEncoding : UTF-8

spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  redis:
    maxActive: 50

management:
  endpoints:
    web:
      exposure:
        include: "*"

auth:
  skipUrls:
    - /ucenter/auth/**
    - /**/sunny/auth/**
    - /**/swagger-ui.html
    - /**/webjars/**
    - /**/swagger-resources/**
    - /**/v2/api-docs
    - /**/doc.html
    - /**/actuator/**
    - /service/access/get_token # 获取令牌接口
    - /service/exec/** # 服务调用接口
